# """
# Name: manifest.yaml
# Description: manifest.yaml
# Created by: Masato Shima
# Created on: 2020/04/05
# """

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-service
  labels:
    app: ftp-service
spec:
  selector:
    matchLabels:
      app: ftp-service
  template:
    metadata:
      labels:
        app: ftp-service
    spec:
      containers:
        - name: ftp-service
          image: masato0921/tutorial-docker-kubernetes:ftp-service

---

apiVersion: v1
kind: Service
metadata:
  name: ftp-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
      app: ftp-service
  ports:
    - port: 20
      protocol: TCP
      name: ftp-20
    - port: 21
      protocol: TCP
      name: ftp-21
    - port: 21100
      protocol: TCP
      name: ftp-21100
    - port: 21101
      protocol: TCP
      name: ftp-21101
  type: LoadBalancer

# End
