# """
# Name: manifest__service.yaml
# Description: sample manifest from chapter 9.6
# Created by: Masato Shima
# Created on: 2020/01/05
# """

apiVersion: v1
kind: Service
metadata:
    name: web-service
spec:
    selector:
        app: web
    ports:
        -   port: 80
            protocol: TCP
    # 以下のコメントアウトを外すことで sessionAffinity を有効化できる
    # sessionAffinity: ClientIP

# End
