# """
# Name: manifest__pod.yaml
# Description: sample manifest from chapter 11.4
# Created by: Masato Shima
# Created on: 2020/01/30
# """

apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: ubuntu
      image: ubuntu:16.04
      volumeMounts:
        - mountPath: /mnt
          name: pvc1
      command:
        - /bin/bin/tail
        - -f
        - /dev/null
  volumes:
    - name: pvc1
      persistentVolumeClaim:
        claimName: data1

# End
