# """
# Name: manifest__pvc.yaml
# Description: sample manifest from chapter 11.4
# Created by: Masato Shima
# Created on: 2020/01/30
# """

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi

# End
