# """
# Name: manifest__nodeport.yaml
# Description: sample manifest from chapter 9.9
# Created by: Masato Shima
# Created on: 2020/01/05
# """

apiVersion: v1
kind: Service
metadata:
    name: web-service-np
spec:
    selector:
        app: web
    ports:
        -   port: 80
            protocol: TCP
    type: NodePort

# End
