# """
# Name: manifest__init_sample.yaml
# Description: sample manifest from chapter 7.5
# Created by: Masato Shima
# Created on: 2020/01/03
# """

apiVersion: v1
kind: Pod
metadata:
    name: init-sample
spec:
    # main container
    containers:
        -   name: main
            image: ubuntu
            command:
                - /bin/sh
            args:
                - -c
                - tail -f
                - /dev/null
            volumeMounts:
                -   mountPath: /docs
                    name: data-vol
                    readOnly: false

    # 初期化 container
    initContainers:
        -   name: init
            image: alpine
            command:
                - /bin/sh
            args:
                - -c
                - midir /mnt/html;
                - chown 33:33 /mnt/html
            volumeMounts:
                -   mountPath: /mnt
                    name: data-vol
                    readOnly: false

    # ポッド上の共有ボリューム
    volumes:
        -   name: data-vol
            emptyDir: {}

# End
