# """
# Name: manifest__task_queue.yaml
# Description: sample manifest from chapter 10.9
# Created by: Masato Shima
# Created on: 2020/01/27
# """

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: CronJob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
  schedule: "*/1 * * * *"

# End
