# """
# Name: manifest__parameters.yaml
# Created by: Masato Shima
# Created on: 2020/03/03
# Description: Argo Workflows: Documentation by Example. chapter.02 Parameters
# """

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-parameters-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
        resources:
          limits:
            memory: 32Mi
            cpu: 100m

# End
