# """
# Name: manifest.yaml
# Description: manifest.yaml
# Created by: Masato Shima
# Created on: 2020/04/05
# """

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-service
  labels:
    app: ftp-service
spec:
  selector:
    matchLabels:
      app: ftp-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ftp-service
    spec:
      containers:
        - name: ftp-service
          image: masato0921/tutorial-docker-kubernetes:ftp-service

---

apiVersion: v1
kind: Service
metadata:
  name: ftp-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    external-dns.alpha.kubernetes.io/hostname: masato-shima.com
spec:
  selector:
    app: ftp-service
  ports:
    - port: 20
      protocol: TCP
      name: ftp-20
    - port: 21
      protocol: TCP
      name: ftp-21
    - port: 21100
      protocol: TCP
      name: ftp-21100
    - port: 21101
      protocol: TCP
      name: ftp-21101
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  selector:
    matchLabels:
      app: ftp-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftp-service
    spec:
      containers:
        - name: external-dns
          image: registry.opensource.zalan.do/teapot/external-dns:latest
          args:
            - --source=service
            - --domain-filter=masato-shima.com
            - --provider=aws
            - --policy=upsert-only
            - --registry=txt
            - --txt-owner-id=my-identifier

# End
