# """
# Name: manifest.yaml
# Description: manifest.yaml
# Created by: Masato Shima
# Created on: 2020/04/05
# """

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-service
  labels:
    app: ftp-service
spec:
  selector:
    matchLabels:
      app: ftp-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ftp-service
    spec:
      containers:
        - name: ftp-service
          image: masato0921/tutorial-docker-kubernetes:ftp-service
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 21100
            - containerPort: 21101
            - containerPort: 21102
            - containerPort: 21103
            - containerPort: 21104
            - containerPort: 21105
          volumeMounts:
            - name: shared-volume
              mountPath: /home/
        - name: transport-service
          image: masato0921/tutorial-docker-kubernetes:transport-service
          volumeMounts:
            - name: shared-volume
              mountPath: /tmp/
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: efs-claim

---

apiVersion: v1
kind: Service
metadata:
  name: ftp-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "5"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: "tutorial-docker-kubernetes-logs"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "tutorial-docker-kubernetes-logs/lb"
    external-dns.alpha.kubernetes.io/hostname: ftp.masato-shima.com
spec:
  type: LoadBalancer
  selector:
    app: ftp-service
  ports:
    - name: ftp-20
      port: 20
      protocol: TCP
      targetPort: 20
    - name: ftp-21
      port: 21
      protocol: TCP
      targetPort: 21
    - name: ftp-21100
      port: 21100
      protocol: TCP
      targetPort: 21100
    - name: ftp-21101
      port: 21101
      protocol: TCP
      targetPort: 21101
    - name: ftp-21102
      port: 21102
      protocol: TCP
      targetPort: 21102
    - name: ftp-21103
      port: 21103
      protocol: TCP
      targetPort: 21103
    - name: ftp-21104
      port: 21104
      protocol: TCP
      targetPort: 21104
    - name: ftp-21105
      port: 21105
      protocol: TCP
      targetPort: 21105

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  selector:
    matchLabels:
      app: ftp-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftp-service
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.opensource.zalan.do/teapot/external-dns:latest
          args:
            - --source=service
            - --domain-filter=masato-shima.com
            - --provider=aws
            - --policy=upsert-only
            - --aws-zone-type=public
            - --registry=txt
            - --txt-owner-id=masato-shima-com-identifier

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: [""]
    resources: ["services","endpoints","pods"]
    verbs: ["get","watch","list"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: default

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-7bfff15a

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com

# End
