# """
# Name: manifest__job_abnormal_end.yaml
# Description: sample manifest from chapter 10.3
# Created by: Masato Shima
# Created on: 2020/01/13
# """

apiVersion: batch/v1
kind: Job
metadata:
    name: normal-end
spec:
    template:
        spec:
            containers:
                -   name: busybox
                    image: busybox:latest
                    command: ["sh", "-c", "sleep 5; exit 1"]
            restartPolicy: Never
    backoffLimit: 3

# End
