# """
# Name: manifest_eksworkshop.yaml
# Created by: Masato Shima
# Created on: 2020/04/30
# Description: template.yaml
# """

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksworkshop-eksctl
  region: ap-northeast-1
managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  iam:
    withAddonPolicies:
      albIngress: true
secretsEncryption:
  keyARN: arn:aws:iam::830310670330:user/QUICKAdministrator

# End
