# """
# Name: manifest__statefulset.yaml
# Description: sample manifest from chapter 12.2
# Created by: Masato Shima
# Created on: 2020/02/23
# """

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql-sts
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: mysql-sts

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql-sts
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-sts
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: qwerty
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: pvc
              subPath: data
          livenessProbe:
            exec:
              command: ["mysqladmin", "-p$MYSQL_ROOT_PASSWORD", "ping"]
            initialDelaySeconds: 60
            timeoutSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 2Gi

# End
