# """
# Name: manifest__webapl_pod.yaml
# Description: sample manifest from chapter 7.4
# Created by: Masato Shima
# Created on: 2020/01/01
# """

apiVersion: v1
kind: Pod
metadata:
    name: webapl
spec:
    containers:
        -   name: webapl
            image: masato0921/tutorial-docker-kubernetes:chapter_007_004
            livenessProbe:
                httpGet:
                    port: 8000
                    path: /health
                initialDelaySeconds: 3
                periodSeconds: 5
            readinessProbe:
                httpGet:
                    port: 8000
                    path: /ready
                initialDelaySeconds: 15
                periodSeconds: 6

# End
